reposervers:
  bonobo:
    type: Bonobo
    url:  <url>
    newrepo:
      Group: <group>
      Administrators: [<user>]
    login:
      Username: <username>
      Password: <password>

  gogs:
    type: Gogs
    url:  https://try.gogs.io/
    newrepo:
      private:  False
    login:
      Token: xxxxxxxx
      Username: <username>

  github:
    type: Github
    url:  https://github.com/
    login:
      Token: xxxxxxxx
      Username: <username>
    ssh:  False


  gitlab:
    type: Gitlab
    url:  https://gitlab.com/
    login:
      Token: xxxxxxxx
      Username: <username>
    ssh:  False
    newrepo:
        group: <groupname>

scripts:
  directory: ~/bin