#reposervers:
#  aarau:
#    type: Bonobo
#    url:  http://scmserver:8080
#    newrepo:
#      Group: PythonPackages
#      Administrators: ["Tobias Schoch"]
#    login:
#      Username: <username>
#      Password: <password>
#  gogs:
#    type: Gogs
#    url:  https://try.gogs.io/
#    newrepo:
#           private:  False
#    login:
#      Username: <username>
#      Password: <password>