reposervers:
  bonobo:
    type: Bonobo
    url:  <url>
    newrepo:
      Group: <group>
      Administrators: [<user>]
    login:
      Username: <username>
      Password: <password>

  gogs:
    type: Gogs
    url:  https://try.gogs.io/
    ssh:  True
    login:
      Token: <token>
      # Username: <username>
      # Password: <password>
    newrepo:
      private:  False

  github:
    type: Github
    url:  https://github.com/
    login:
      Token: <token>
      # Username: <username>
      # Password: <password>

    ssh:  False

  gitlab:
    type: Gitlab
    url:  https://gitlab.com/
    login:
      Token: <token>
      # Username: <username>
      # Password: <password>
    ssh:  False
    newrepo:
        group: <groupname>

scripts:
  directory: ~/bin